import type { UIActionId } from "./actions";
export type UIActionSurface = "player" | "queue" | "help" | "matrix" | "dashboard";
export type UIActionState = "ACTIVE" | "DISABLED" | "CONDITIONAL";
export type UIInteractionKind = "button" | "select" | "modal";
export interface UIActionDefinition {
  readonly id:UIActionId; readonly label:string; readonly surface:UIActionSurface;
  readonly state:UIActionState; readonly description:string; readonly interaction:UIInteractionKind;
}
const definitions = new Map<UIActionId, UIActionDefinition>();
export function defineUIAction(definition:UIActionDefinition):void { if(definitions.has(definition.id)) throw new Error(`Duplicate UI action: ${definition.id}`); definitions.set(definition.id,Object.freeze({...definition})); }
export function getUIAction(id:string):UIActionDefinition|undefined{return definitions.get(id as UIActionId);}
export function listUIActions():readonly UIActionDefinition[]{return Object.freeze([...definitions.values()].sort((a,b)=>a.id.localeCompare(b.id)));}
export function assertUIActionKnown(id:string):UIActionId { const found=getUIAction(id); if(!found) throw new Error(`Unknown UI action: ${id}`); return found.id; }
export function uiActionRegistryAudit(){const values=listUIActions();const ids=new Set<string>();let invalid=0;for(const x of values){if(!x.id||!x.label||!x.surface||!x.description||!x.interaction)invalid++;ids.add(x.id);}return {total:values.length,duplicates:values.length-ids.size,invalid,sealed:values.length>0&&invalid===0&&ids.size===values.length};}
import { UIAction } from "./actions";
const b=(id:UIActionId,label:string,surface:UIActionSurface,state:UIActionState,description:string,interaction:UIInteractionKind="button")=>({id,label,surface,state,description,interaction});
const builtInDefinitions: ReadonlyArray<UIActionDefinition> = [
 b(UIAction.PLAYER_PREVIOUS,"◀ PREV","player","CONDITIONAL","Play the previous track"), b(UIAction.PLAYER_PLAY_PAUSE,"Ⅱ PAUSE","player","CONDITIONAL","Pause or resume playback"), b(UIAction.PLAYER_SKIP,"SKIP ▶","player","CONDITIONAL","Skip the current track"), b(UIAction.PLAYER_LOOP,"LOOP","player","ACTIVE","Cycle loop mode"), b(UIAction.PLAYER_SHUFFLE,"SHUFFLE","player","CONDITIONAL","Shuffle upcoming tracks"), b(UIAction.PLAYER_QUEUE,"QUEUE","player","ACTIVE","Open the live queue"), b(UIAction.PLAYER_LYRICS,"LYRICS","player","ACTIVE","Open lyrics workflow"), b(UIAction.PLAYER_FAVORITE,"FAVORITE","player","CONDITIONAL","Save the current track"), b(UIAction.PLAYER_REFRESH,"REFRESH","player","ACTIVE","Refresh live player state"), b(UIAction.PLAYER_MATRIX,"MATRIX","player","ACTIVE","Open command matrix"), b(UIAction.PLAYER_DASHBOARD,"CONTROL CENTER","dashboard","ACTIVE","Open control center"), b(UIAction.PLAYER_CLOSE,"× CLOSE","player","ACTIVE","Close the surface"), b(UIAction.PLAYER_VOLUME_DOWN,"VOL −","player","CONDITIONAL","Decrease player volume"), b(UIAction.PLAYER_VOLUME_MUTE,"MUTE","player","CONDITIONAL","Mute or restore volume"), b(UIAction.PLAYER_VOLUME_UP,"VOL +","player","CONDITIONAL","Increase player volume"), b(UIAction.PLAYER_REPLAY,"REPLAY","player","CONDITIONAL","Restart current track"), b(UIAction.PLAYER_STOP,"STOP","player","CONDITIONAL","Stop playback"), b(UIAction.QUEUE_PREVIOUS,"◀ PREV","queue","CONDITIONAL","Previous queue page"), b(UIAction.QUEUE_NEXT,"NEXT ▶","queue","CONDITIONAL","Next queue page"), b(UIAction.HELP_CATEGORY,"SELECT MODULE","help","ACTIVE","Open a command module","select"), b(UIAction.HELP_BACK,"◀ MODULE MATRIX","help","ACTIVE","Return to module matrix"), b(UIAction.HELP_SEARCH,"⌕ SEARCH","help","ACTIVE","Search the live command registry"), b(UIAction.HELP_SEARCH_SUBMIT,"SEARCH SUBMIT","help","ACTIVE","Submit a live command search","modal"), b(UIAction.MATRIX_REFRESH,"REFRESH","matrix","ACTIVE","Refresh the command matrix"), b(UIAction.MATRIX_BACK,"◀ BACK","matrix","ACTIVE","Return from command matrix"), b(UIAction.DASHBOARD_REFRESH,"⌁ REFRESH","dashboard","ACTIVE","Refresh the control center"), b(UIAction.DASHBOARD_QUEUE,"QUEUE","dashboard","ACTIVE","Open the live queue"), b(UIAction.DASHBOARD_VOLUME,"VOLUME","dashboard","ACTIVE","Open volume controls"), b(UIAction.DASHBOARD_EFFECTS,"EFFECTS","dashboard","ACTIVE","Toggle the server effects system"), b(UIAction.DASHBOARD_AUTOPLAY,"AUTOPLAY","dashboard","ACTIVE","Toggle server autoplay"), b(UIAction.DASHBOARD_SOURCE,"SOURCE","dashboard","ACTIVE","Cycle the default source"), b(UIAction.DASHBOARD_PLAYER,"PLAYER","dashboard","ACTIVE","Return to the live player")
];
for(const definition of builtInDefinitions) if(!definitions.has(definition.id)) definitions.set(definition.id,Object.freeze(definition));
