/** NOIR MUSIC — Canonical runtime UI action vocabulary. */
export const UIAction = Object.freeze({
  PLAYER_PREVIOUS: "mono:v8:previous",
  PLAYER_PLAY_PAUSE: "mono:v8:playpause",
  PLAYER_SKIP: "mono:v8:skip",
  PLAYER_LOOP: "mono:v8:loop",
  PLAYER_SHUFFLE: "mono:v8:shuffle",
  PLAYER_QUEUE: "mono:v8:queue",
  PLAYER_LYRICS: "mono:v8:lyrics",
  PLAYER_FAVORITE: "mono:v8:favorite",
  PLAYER_REFRESH: "mono:v8:refresh",
  PLAYER_MATRIX: "mono:v8:matrix",
  PLAYER_DASHBOARD: "mono:v8:dashboard",
  PLAYER_CLOSE: "mono:v8:close",
  PLAYER_VOLUME_DOWN: "mono:v8:volume:down",
  PLAYER_VOLUME_MUTE: "mono:v8:volume:mute",
  PLAYER_VOLUME_UP: "mono:v8:volume:up",
  PLAYER_REPLAY: "mono:v8:replay",
  PLAYER_STOP: "mono:v8:stop",
  QUEUE_PREVIOUS: "mono:v8:queue:prev",
  QUEUE_NEXT: "mono:v8:queue:next",
  HELP_CATEGORY: "mono:v8:help:category",
  HELP_BACK: "mono:v8:help:back",
  HELP_SEARCH: "mono:v8:help:search",
  HELP_SEARCH_SUBMIT: "mono:v8:help:search:submit",
  MATRIX_REFRESH: "mono:v8:matrix:refresh",
  MATRIX_BACK: "mono:v8:matrix:back",
  DASHBOARD_REFRESH: "mono:v8:dashboard:refresh",
  DASHBOARD_QUEUE: "mono:v8:dashboard:queue",
  DASHBOARD_VOLUME: "mono:v8:dashboard:volume",
  DASHBOARD_EFFECTS: "mono:v8:dashboard:effects",
  DASHBOARD_AUTOPLAY: "mono:v8:dashboard:autoplay",
  DASHBOARD_SOURCE: "mono:v8:dashboard:source",
  DASHBOARD_PLAYER: "mono:v8:dashboard:player",
} as const);
export type UIActionId = typeof UIAction[keyof typeof UIAction];
export const UI_ACTION_IDS: readonly UIActionId[] = Object.freeze(Object.values(UIAction));
