/** GLYPH-25 strength core: deterministic, normalized, bounded discovery semantics; never executes commands. */
export interface PaletteCommand{name:string;category:string;summary:string;aliases?:string[];keywords?:string[];enabled?:boolean;}
export interface PaletteResult extends PaletteCommand{score:number;matchedBy:string[];}
const norm=(s:unknown)=>String(s??"").normalize("NFKC").replace(/[\r\n]+/g," ").replace(/[\u0000-\u001F\u007F]/g," ").trim().toLowerCase();
const safe=(a:unknown[],cap=25)=>Array.isArray(a)?a.map(norm).filter(Boolean).slice(0,cap):[];
export function scoreCommand(c:PaletteCommand,q:string):number{const needle=norm(q),name=norm(c.name);if(!needle)return 1;if(name===needle)return 100;if(name.startsWith(needle))return 80;const hay=[c.name,c.category,c.summary,...safe(c.aliases??[]),...safe(c.keywords??[])].map(norm).join(" ");if(hay.includes(needle))return 50;const parts=needle.split(/\s+/).filter(Boolean);return parts.length&&parts.every(x=>hay.includes(x))?30:0;}
export function searchPalette(commands:PaletteCommand[],query:string,limit=12):PaletteResult[]{const q=norm(query).slice(0,120),cap=Math.max(1,Math.min(25,Number.isFinite(limit)?Math.floor(limit):12));return (Array.isArray(commands)?commands:[]).filter(c=>c&&c.enabled!==false).map(c=>{const fields=[c.name,c.category,...safe(c.aliases??[]),...safe(c.keywords??[])];return {...c,name:norm(c.name).slice(0,100),category:norm(c.category).slice(0,80),summary:norm(c.summary).slice(0,300),score:scoreCommand(c,q),matchedBy:fields.filter(x=>norm(x).includes(q)).map(norm).slice(0,10)};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).slice(0,cap);}
export function paletteGroups(results:PaletteResult[]):Map<string,PaletteResult[]>{const m=new Map<string,PaletteResult[]>();for(const r of Array.isArray(results)?results:[]){const k=norm(r.category)||"other";m.set(k,[...(m.get(k)??[]),r]);}return m;}
export function paletteHealth(commands:PaletteCommand[]):string[]{const errors:string[]=[],seen=new Set<string>();for(const c of Array.isArray(commands)?commands:[]){const k=norm(c?.name);if(!k)errors.push("NAME_EMPTY");if(k.length>100)errors.push(`NAME_LONG:${k.slice(0,100)}`);if(seen.has(k))errors.push(`DUPLICATE:${k}`);seen.add(k);}return [...new Set(errors)];}
