/** GLYPH-25 strength core: immutable, finite, canonical visual truth. */
export type TokenScale="xs"|"sm"|"md"|"lg"|"xl"|"xxl";
export type TokenDensity="mini"|"compact"|"standard"|"dense"|"operator";
export interface DesignTokenSet{spacing:Record<TokenScale,number>;widths:Record<TokenScale,number>;rows:Record<TokenScale,number>;density:TokenDensity;border:string;divider:string;ink:string;muted:string;inverse:string;}
const SCALES:readonly TokenScale[]=["xs","sm","md","lg","xl","xxl"],DENSITIES:readonly TokenDensity[]=["mini","compact","standard","dense","operator"];
const BASE:DesignTokenSet={spacing:{xs:1,sm:2,md:4,lg:6,xl:8,xxl:12},widths:{xs:8,sm:16,md:24,lg:32,xl:48,xxl:64},rows:{xs:1,sm:2,md:3,lg:4,xl:6,xxl:8},density:"standard",border:"┌─┐│└┘",divider:"─",ink:"█",muted:"·",inverse:"░"};
export const GLYPH22_TOKENS:Readonly<DesignTokenSet>=Object.freeze(BASE);
export interface SemanticRole{name:string;emphasis:number;glyph:string;readable:string;}
export const SEMANTIC_ROLES:Readonly<Record<string,SemanticRole>>=Object.freeze({primary:{name:"primary",emphasis:4,glyph:"◆",readable:"primary"},secondary:{name:"secondary",emphasis:2,glyph:"◇",readable:"secondary"},success:{name:"success",emphasis:4,glyph:"✓",readable:"success"},warning:{name:"warning",emphasis:3,glyph:"!",readable:"warning"},danger:{name:"danger",emphasis:5,glyph:"×",readable:"danger"},info:{name:"info",emphasis:2,glyph:"i",readable:"information"},muted:{name:"muted",emphasis:1,glyph:"·",readable:"muted"}});
const hasScale=(x:unknown):x is TokenScale=>typeof x==="string"&&SCALES.includes(x as TokenScale),hasDensity=(x:unknown):x is TokenDensity=>typeof x==="string"&&DENSITIES.includes(x as TokenDensity);
const finiteInt=(x:unknown,f:number,min:number,max:number)=>{const n=typeof x==="number"&&Number.isFinite(x)?Math.floor(x):f;return Math.max(min,Math.min(max,n));};
const cleanGlyph=(x:unknown,fallback:string)=>{const s=String(x??"").replace(/[\r\n\u0000-\u001F\u007F]/g,"");return [...s][0]||fallback;};
export function token(scale:TokenScale,key:"spacing"|"widths"|"rows"):number{return GLYPH22_TOKENS[key][hasScale(scale)?scale:"md"];}
export function role(name:string):SemanticRole{return SEMANTIC_ROLES[String(name??"").trim().toLowerCase()]??SEMANTIC_ROLES.secondary;}
export function densityToken(density:TokenDensity):DesignTokenSet{return normalizeTokens({density});}
export function normalizeTokens(tokens:Partial<DesignTokenSet>={}):DesignTokenSet{const source=tokens??{},out:DesignTokenSet={...BASE,spacing:{...BASE.spacing},widths:{...BASE.widths},rows:{...BASE.rows}};for(const s of SCALES){out.spacing[s]=finiteInt(source.spacing?.[s],BASE.spacing[s],0,120);out.widths[s]=finiteInt(source.widths?.[s],BASE.widths[s],1,120);out.rows[s]=finiteInt(source.rows?.[s],BASE.rows[s],1,50);}out.density=hasDensity(source.density)?source.density:BASE.density;out.border=cleanGlyph(source.border,BASE.border);out.divider=cleanGlyph(source.divider,BASE.divider);out.ink=cleanGlyph(source.ink,BASE.ink);out.muted=cleanGlyph(source.muted,BASE.muted);out.inverse=cleanGlyph(source.inverse,BASE.inverse);return out;}
export function tokenHealth(tokens:DesignTokenSet=BASE):string[]{const t=normalizeTokens(tokens),e:string[]=[];for(const k of SCALES){if(t.spacing[k]<0)e.push(`INVALID_SPACING:${k}`);if(t.widths[k]<1)e.push(`INVALID_WIDTH:${k}`);if(t.rows[k]<1)e.push(`INVALID_ROWS:${k}`);}if(!hasDensity(t.density))e.push("INVALID_DENSITY");if(!t.divider||!t.ink||!t.muted)e.push("GLYPH_MISSING");for(const k of ["border","divider","ink","muted","inverse"] as const)if([...t[k]].length!==1)e.push(`GLYPH_ARITY:${k}`);return [...new Set(e)];}
export function tokenSnapshot(tokens:DesignTokenSet=BASE):DesignTokenSet{const t=normalizeTokens(tokens);return {spacing:{...t.spacing},widths:{...t.widths},rows:{...t.rows},density:t.density,border:t.border,divider:t.divider,ink:t.ink,muted:t.muted,inverse:t.inverse};}
export function tokenSeal(tokens:DesignTokenSet=BASE):"SEALED"|"REPAIRED"{return tokenHealth(tokens).length?"REPAIRED":"SEALED";}
