/** GLYPH-25 strength core: sanitized telemetry, monotonic clocks and bounded rendering. */
export type DeckState="PLAYING"|"PAUSED"|"IDLE"|"LOADING"|"ERROR";
export interface PlayerDeck{title:string;artist:string;source?:string;requester?:string;positionMs:number;durationMs:number;volume:number;state:DeckState;queueSize:number;node?:string;}
const text=(x:unknown,fallback="—")=>{const v=String(x??"").replace(/[\r\n]+/g," ").replace(/[\u0000-\u001F\u007F]/g," ").trim();return v?v.slice(0,180):fallback;};
const ms=(x:unknown)=>typeof x==="number"&&Number.isFinite(x)?Math.max(0,Math.min(86400000,Math.floor(x))):0;
export function deckProgress(d:PlayerDeck,width=28):string{const w=Math.max(1,Math.min(80,Number.isFinite(width)?Math.floor(width):28)),duration=ms(d.durationMs),position=Math.min(ms(d.positionMs),duration),ratio=duration?position/duration:0,fill=Math.max(0,Math.min(w,Math.round(w*ratio)));return "█".repeat(fill)+"·".repeat(w-fill);}
export function deckClock(value:number):string{const s=Math.floor(ms(value)/1000);return `${Math.floor(s/60).toString().padStart(2,"0")}:${(s%60).toString().padStart(2,"0")}`;}
export function deckLines(d:PlayerDeck):string[]{const safe=normalizeDeck(d),volume=Math.max(0,Math.min(200,Math.floor(safe.volume))),queue=Math.max(0,Math.min(100000,Math.floor(safe.queueSize)));return [`[ ${safe.state} ] ${text(safe.title,"UNTITLED")}`,`ARTIST // ${text(safe.artist,"UNKNOWN")}`,`${deckClock(safe.positionMs)} ${deckProgress(safe)} ${deckClock(safe.durationMs)}`,`VOL ${volume}%  QUEUE ${queue}`,`SRC ${text(safe.source)}  NODE ${text(safe.node)}`];}
export function deckActions(d:PlayerDeck):string[]{const s=normalizeDeck(d).state;return s==="PLAYING"?["PAUSE","SKIP","QUEUE","STOP"]:s==="PAUSED"?["RESUME","SKIP","QUEUE","STOP"]:["PLAY","QUEUE","SEARCH","HELP"];}
export function normalizeDeck(d:PlayerDeck):PlayerDeck{const duration=ms(d?.durationMs),position=Math.min(ms(d?.positionMs),duration||ms(d?.positionMs));return {...d,title:text(d?.title,"UNTITLED"),artist:text(d?.artist,"UNKNOWN"),positionMs:position,durationMs:duration,volume:Math.max(0,Math.min(200,Math.floor(typeof d?.volume==="number"&&Number.isFinite(d.volume)?d.volume:0))),queueSize:Math.max(0,Math.min(100000,Math.floor(typeof d?.queueSize==="number"&&Number.isFinite(d.queueSize)?d.queueSize:0))),source:d?.source?text(d.source,""):undefined,requester:d?.requester?text(d.requester,""):undefined,node:d?.node?text(d.node,""):undefined,state:(['PLAYING','PAUSED','IDLE','LOADING','ERROR'] as const).includes(d?.state)?d.state:"IDLE"};}
export function deckHealth(d:PlayerDeck):string[]{const s=normalizeDeck(d),e:string[]=[];if(d?.durationMs<0||d?.positionMs<0)e.push("TIME_NEGATIVE");if(d?.positionMs>d?.durationMs&&d?.durationMs>0)e.push("POSITION_OVER_DURATION");if(d?.volume<0||d?.volume>200)e.push("VOLUME_RANGE");if(d?.queueSize<0)e.push("QUEUE_NEGATIVE");return [...new Set(e)];}
